services:
  - type: web
    name: hackrx-qa-api
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: PORT
        value: 10000
      - key: GEMINI_API_KEY
        value: 'AIzaSyBlVAGaEchXF46DbcNFE66X6HbbcN4oSXI'  # Or set manually in dashboard
      - key: PYTHON_VERSION
        value: "3.10.9"           # Enforces Python 3.10 runtime
    pythonVersion: 3.10           # Optional if not working via envVar
